### ISSUE TITLE
Can't arm/disarm when panel is locked

### ISSUE THREAD

**Issue by eric-cagewrx** [XaF/qolsysgw#16]
I've enabled the 6 digit user code. If the panel is unlocked I can arm/disarm from HA. I only get this message if the panel is locked. Is this intended behavior? I have a correct 6 digit user code in my app.yaml since it unlocks when the panel is unlocked. I use partitions and was wondering if that was part of my problem.

2022-03-01 07:38:34.175743 DEBUG qolsys_panel: Unknown Qolsys event: {"event":"ERROR","partition_id":0,"error_type":"usercode","description":"Please Enable Six Digit User Code or KeyPad is already Locked","version":1,"nonce":"qolsys","requestID":"07090977-1fcb-4832-880e-8fb6c673f3cb"}

apps.yaml
```
qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: redacted
  panel_token: redacted
  panel_user_code: redacted
  panel_mac: redacted
  # ha_user_code: 1234
  # code_disarm_required: true
  # code_arm_required: true
  # ha_check_user_code: true
  log_level: DEBUG
  mqtt_namespace: mqtt
```

appdaemon.yaml
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: redacted
  longitude: redacted
  elevation: 100
  time_zone: America/Los_Angeles
  plugins:
    HASS:
      type: hass
    # And we need to add the MQTT plugin
    MQTT:
      type: mqtt
      namespace: mqtt # We will need that same value in the apps.yaml configuration
      client_host: 192.168.0.60 # The IP address or hostname of the MQTT broker
      client_port: 1883 # The port of the MQTT broker, generally 1883
      client_user: mqtt
      client_password: redacted
http:
  url: http://127.0.0.1:5050
hadashboard:
admin:
api:
```
