### ISSUE TITLE
Invalid session token when trying to disarm

### ISSUE THREAD

**Issue by CitizenRacer** [XaF/qolsysgw#17]
Hello,

My panel is working great with home-assistant. I can see all of my sensors but when I try to arm, nothing happens. When I look in the AppDaemon logs, I get this error message:

`ERROR qolsys_panel: invalid session token for <QolsysControlArmHome partition_id=0 code=None session_token=82841e9e-22d9-4217-a4f2-e30c3bf29919>`

I am sure this is a mistake I'm making, but my google fu isn't helping me find anything.

Here is my appdaemon.yaml
`

          secrets: /config/secrets.yaml
          
          appdaemon:
            latitude: XXXXX
            longitude: -XXXXX
            elevation: 2
            time_zone: America/Los_Angeles
            production_mode: False
            plugins:
              HASS:
                type: hass
                ha_url: http://192.168.1.8:8123
                token: !secret appdaemon_ha_token
                cert_verify: false
                namespace: default
          
              MQTT:
                type: mqtt
                namespace: mqtt
                client_host: 192.168.1.8
                client_port: 1883
                client_user: homeassistant
                client_password: !secret mqtt_password
`

Here is my apps.yaml:

`
```
        qolsys_panel:
            module: gateway
            class: QolsysGateway
            panel_host: x.x.x.x
            panel_mac: xx:xx:xx:xx:xx:xx
            panel_token: xxxxxx
            panel_user_code: xxxx
            code_arm_required: false
            code_disarm_required: true
            ha_check_user_code: false # we want Qolsys Gateway to receive the code and perform the check
```
`
