### ISSUE TITLE
Can't disarm with correct user code

### ISSUE THREAD

**Issue by ifeign** [XaF/qolsysgw#54]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

I finally got around to migrating to your Qolsys integration and got everything working after a few issues with MQTT (ended up removing and resinstalling it and all my devices showed up). Disarming worked fine with the old integration.

UPDATE:
It gets even weirder.. I set `code_disarm required: true` and it works if I input the code in HASS

Everything works, except for disarming. Appdaemon log shows
`2022-12-29 21:18:21.207410 ERROR qolsys_panel: Code received in the control command invalid for control event <QolsysControlDisarm partition_id=0 code=None session_token=0f7ffb47-cce5-4872-8b52-35dfedc7f527>`

apps.yaml looks like this
```
qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: 192.168.XX.XX
  panel_mac: XX:XX:XX:XX:XX:XX
  panel_token: XXXXXX
  panel_user_code: XXXX
  arm_away_exit_delay: 0
  code_disarm_required: false
  ha_check_user_code: false
```

I looked through some old issues and I saw one related to partitions, but it seems that I don't have those enabled.

### Expected behavior

Disarm my security system

### DEBUG logs

2022-12-29 21:18:21.207410 ERROR qolsys_panel: Code received in the control command invalid for control event <QolsysControlDisarm partition_id=0 code=None session_token=0f7ffb47-cce5-4872-8b52-35dfedc7f527>
