### ISSUE TITLE
Feature request: Add a last error message entity

### ISSUE THREAD

**Issue by CitizenRacer** [XaF/qolsysgw#80]
The last_error time entity is super useful. I'd love to have a text field that goes with it that easily displays what the last error was. It'll make it much easier to start digging in on what to repair.

**Comment by XaF** [comment]
You can create that directly in Home Assistant. You can create a sensor that tracks an attribute of another sensor, in this case the last error message available as attribute of the last error sensor!

**Comment by XaF** [comment]
I believe something like:

```yaml
template:
  - sensor:
      - name: qolsys_panel_last_error_desc
        state: "{{state_attr('sensor.qolsys_panel_last_error', 'desc')}}"
```
